# Change these first
owner: favelacityrp # Your GitHub organization or username, where this repository lives
repo: favelacitystatus # The name of this repository

sites:
  - name: Favela City RP Server
    url: http://185.91.127.93/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: dark
  # cname: 	favela-status.serverpit.com
  favicon: https://s11.gifyu.com/images/SA7tj.png
  baseUrl: /favelacitystatus
  logoUrl: https://s1.gifyu.com/images/SA7fM.gif
  name: Favela City RP Status
  introTitle: "**Favel City RP Status**"
  introMessage: Dies ist die Status-Seite vom Favela-City RP Server. Für weitere Informationen könnt ihr unserem [Discord](https://discord.com/invite/favela-city) joinen.
  navbar:
    - title: FiveM Server
      href: https://cfx.re/join/egg5em
    - title: Discord
      href: https://discord.com/invite/favela-city
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
