# Change these first
owner: favelacityrp # Your GitHub organization or username, where this repository lives
repo: favelacitystatus # The name of this repository

sites:
  - name: Favela City RP Server
    url: $SERVER_URL
    maxResponseTime: 1050

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: dark
  # cname: 	favela-status.serverpit.com
  favicon: https://s11.gifyu.com/images/SA7tj.png
  baseUrl: /favelacitystatus
  logoUrl: https://s1.gifyu.com/images/SA7fM.gif
  name: Favela City RP Status
  introTitle: "**Favel City RP Status**"
  introMessage: Dies ist die Status-Seite vom Favela-City RP Server. Für weitere Informationen könnt ihr unserem [Discord](https://discord.com/invite/favela-city) joinen.
  navbar:
    - title: FiveM Server
      href: https://cfx.re/join/egg5em
    - title: Discord
      href: https://discord.com/invite/favela-city
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  customBodyHtml: <div class="max-w-3xl mx-auto mt-10 text-center mb-10"><p class="text-lg text-neutral-300">Danke für die vielen Reports in unserer Beta! Wir werden unseren Server bald releasen.</p></div>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: © 2024 Favela City
